window.PizzaTypes = {
  normal: "normal",
  spicy: "spicy",
  veggie: "veggie",
  fungi: "fungi",
  chill: "chill",
}

window.Pizzas = {
  "s001": {
    name: "Rebanada Samurai",
    description: "Pizza desc here",
    type: PizzaTypes.spicy,
    src: "/images/characters/pizzas/s001.png",
    icon: "/images/icons/spicy.png",
    actions: [ "saucyStatus", "clumsyStatus", "damage1" ],
  },
  "s002": {
    name: "Brigada tocino",
    description: "A salty warrior who fears nothing",
    type: PizzaTypes.spicy,
    src: "/images/characters/pizzas/s002.png",
    icon: "/images/icons/spicy.png",
    actions: [ "damage1", "saucyStatus", "clumsyStatus" ],
  },
  "v001": {
    name: "Llamame Kale",
    description: "Pizza desc here",
    type: PizzaTypes.veggie,
    src: "/images/characters/pizzas/v001.png",
    icon: "/images/icons/veggie.png",
    actions: [ "damage1" , "clumsyStatus"],
  },
  "v002": {
    name: "Archie Artichoke",
    description: "Pizza desc here",
    type: PizzaTypes.veggie,
    src: "/images/characters/pizzas/v001.png",
    icon: "/images/icons/veggie.png",
    actions: [ "damage1" , "saucyStatus"],
  },
  "f001": {
    name: "Portobello Express",
    description: "Pizza desc here",
    type: PizzaTypes.fungi,
    src: "/images/characters/pizzas/f001.png",
    icon: "/images/icons/fungi.png",
    actions: [ "damage1" , "clumsyStatus"],
  },
  "f002": {
    name: "Dime Shitake",
    description: "Pizza desc here",
    type: PizzaTypes.fungi,
    src: "/images/characters/pizzas/f001.png",
    icon: "/images/icons/fungi.png",
    actions: [ "damage1" , "saucyStatus"],
  },
  "n001": {
    name: "Triple queso",
    description: "Pizza con triple de queso normal",
    type: PizzaTypes.normal,
    src: "/images/characters/pizzas/n001.png",
    icon: "/images/icons/normal.png",
    actions: [ "damage1" , "coolStatus", "saucyStatus"],
  },
  "n002": {
    name: "Extravaganza",
    description: "Pizza con con verdura y carne ",
    type: PizzaTypes.normal,
    src: "/images/characters/pizzas/n002.png",
    icon: "/images/icons/normal.png",
    actions: [ "damage1" , "coolStatus", "saucyStatus"],
  },
  "n003": {
    name: "Carnes frias",
    description: "Pizza carnivora",
    type: PizzaTypes.normal,
    src: "/images/characters/pizzas/n003.png",
    icon: "/images/icons/normal.png",
    actions: [ "damage3" , "clumsyStatus", "saucyStatus"],
  },
  "n004": {
    name: "Portuguesa",
    description: "Pizza con... Huevo?",
    type: PizzaTypes.normal,
    src: "/images/characters/pizzas/n004.png",
    icon: "/images/icons/normal.png",
    actions: [ "damage1" , "coolStatus", "damage5"],
  }
}